name: Eleventy Build

on:
  push:
    branches:
      - main

jobs:
  build-to-gh-pages-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - run: yarn

      - run: yarn add sharp --ignore-engines
      
      - run: yarn run build:prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.BLERG_DEPLOY }}
          publish_dir: ./_site
